[workspace]
 members=[
        "mainProject1",
        "mainProject2",
        "rc_demo",
        "msglib",
        "netlib",
        "thread_demo",
        "move_demo",
        "network_server"
    ]